import Link from 'next/link'
import { ClerkProvider } from '@clerk/nextjs'
import { dark } from '@clerk/themes'

import { Inter } from 'next/font/google'
import './globals.css'

import Footer from '@/components/Footer'
import Head from 'next/head'
import Header from '@/components/header'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'KryssonForge',
  description: 'Generated by create next app'
}

export default function RootLayout({ children }) {
  return (
    <ClerkProvider appearance={{ baseTheme: dark }}>
      <html lang='en'>
        <body className={inter.className}>
          <Header /> {/* Add the Header component */}
          <main>{children}</main>
          <Footer /> {/* Add the Footer component */}
        </body>
      </html>
    </ClerkProvider>
  )
}
